//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAndTunes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заместитель начальника цеха по энергооборудованию")]
        public string ReportSignatory1Position {
            get {
                return ((string)(this["ReportSignatory1Position"]));
            }
            set {
                this["ReportSignatory1Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Начальник участка неразрущающих средств контроля")]
        public string ReportSignatory2Position {
            get {
                return ((string)(this["ReportSignatory2Position"]));
            }
            set {
                this["ReportSignatory2Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("А.Н. Елькин")]
        public string ReportSignatory1FullName {
            get {
                return ((string)(this["ReportSignatory1FullName"]));
            }
            set {
                this["ReportSignatory1FullName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("С.А. Медведев")]
        public string ReportSignatory2FullName {
            get {
                return ((string)(this["ReportSignatory2FullName"]));
            }
            set {
                this["ReportSignatory2FullName"] = value;
            }
        }
    }
}
