//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAndTunes.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Normative
    {
        public string WorkArea { get; set; }
        public string DefectoscopeName { get; set; }
        public string Operation { get; set; }
        public System.DateTime BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.TimeSpan Value { get; set; }
    }
}
